name: verdict
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - anyio==4.12.0
      - certifi==2025.11.12
      - cvss==3.6
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - faiss-cpu==1.13.1
      - httpx-sse==0.4.3
      - idna==3.11
      - jiter==0.12.0
      - joblib==1.5.3
      - langchain==1.1.2
      - langchain-community==0.3.31
      - langchain-core==1.1.1
      - langchain-openai==1.1.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.14
      - langsmith==0.4.56
      - marshmallow==3.26.1
      - mypy-extensions==1.1.0
      - openai==2.9.0
      - ormsgpack==1.12.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - unidiff==0.7.5
      - urllib3==2.6.0
      - uuid-utils==0.12.0
      - xxhash==3.6.0